# Align with the Serial LTE Modem (SLM) application.
CONFIG_MODEM_CMUX_MTU=127
CONFIG_MODEM_CMUX_WORK_BUFFER_SIZE=536
CONFIG_MODEM_CMUX_LOG_LEVEL_DBG=y
CONFIG_MODEM_CELLULAR_UART_BUFFER_SIZES=6000
CONFIG_MODEM_CELLULAR_PERIODIC_SCRIPT_MS=60000

# Run Native sim in real-time mode.
CONFIG_NATIVE_SIM_SLOWDOWN_TO_REAL_TIME=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=y
CONFIG_NET_L2_PPP=y
CONFIG_NET_L2_ETHERNET=n
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_CONTEXT_RCVTIMEO=y

# DNS
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER_MAX_SERVERS=4
CONFIG_ZVFS_POLL_MAX=5
CONFIG_NET_L2_PPP_OPTION_DNS_USE=y

# Network management
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_CONNECTION_MANAGER=y

# Modem driver
CONFIG_MODEM=y
CONFIG_MODEM_CELLULAR=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_SHELL=y
#CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SHELL_BACKEND_SERIAL_API_POLLING=y
CONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=n

CONFIG_ZVFS_POLL_MAX=20
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_RUNTIME_USE_DEDICATED_WQ=y
CONFIG_PM_DEVICE_SHELL=y

CONFIG_GPIO=y
CONFIG_GPIO_EMUL=y
CONFIG_GPIO_SHELL=y

CONFIG_MODEM_AT_SHELL=n
CONFIG_MODEM_AT_USER_PIPE=n
